---
version: "3.7"
services:
  redis:
    image: redis:alpine
    restart: always
  discord-command-bot:
    image: fortressone/discord-bot:latest
    command: server
    restart: always
    depends_on:
      - redis
    volumes:
      - type: bind
        source: "/home/ubuntu/.config/qwtf_discord_bot/config.yaml"
        target: /discord-bot/config.yaml
  discord-watcher-bot:
    image: fortressone/discord-bot:latest
    command: watcher
    restart: always
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis
    volumes:
      - type: bind
        source: "/home/ubuntu/.config/qwtf_discord_bot/config.yaml"
        target: /discord-bot/config.yaml
  discord-pug-bot:
    image: fortressone/discord-bot:latest
    command: pug
    restart: always
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis
    volumes:
      - type: bind
        source: "/home/ubuntu/.config/qwtf_discord_bot/config.yaml"
        target: /discord-bot/config.yaml
